// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfvwaXHiti71LOL6uvYaeHR4DOWFkNVR4',
    appId: '1:1023091135644:web:86797d99c51ac033748959',
    messagingSenderId: '1023091135644',
    projectId: 'crystal-2ab9d',
    authDomain: 'crystal-2ab9d.firebaseapp.com',
    storageBucket: 'crystal-2ab9d.appspot.com',
    measurementId: 'G-KG5XP6E3M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeXwmvmkwuB7j8d9UbFIm0rYg5jaiOkFo',
    appId: '1:1023091135644:android:dc2c055815d21462748959',
    messagingSenderId: '1023091135644',
    projectId: 'crystal-2ab9d',
    storageBucket: 'crystal-2ab9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZByQqivyZyxnx4oX-HYY3Eu0sAN2Koyw',
    appId: '1:1023091135644:ios:7d93b721b49b7583748959',
    messagingSenderId: '1023091135644',
    projectId: 'crystal-2ab9d',
    storageBucket: 'crystal-2ab9d.appspot.com',
    iosClientId: '1023091135644-9stji3eh8sba4q3pm6kbg5ua069hulg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.checklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZByQqivyZyxnx4oX-HYY3Eu0sAN2Koyw',
    appId: '1:1023091135644:ios:50a69ba17c22ff2a748959',
    messagingSenderId: '1023091135644',
    projectId: 'crystal-2ab9d',
    storageBucket: 'crystal-2ab9d.appspot.com',
    iosClientId: '1023091135644-f5bceiubf1hm1gn3g34k0tjssec7a90a.apps.googleusercontent.com',
    iosBundleId: 'com.example.checklist.RunnerTests',
  );
}
